CREATE TABLE lists (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE tasks (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    is_done BOOLEAN DEFAULT FALSE,
    list_id INT UNSIGNED,
    FOREIGN KEY (list_id) REFERENCES lists(id) ON DELETE CASCADE
);